### ISSUE TITLE
Manner of death order does not reflect the international death certificates and how people read it. 

### ISSUE THREAD

**Issue by samsontu** [ICD-API/electronic-death-certificate-format#1]
As commented by Kathy O'Brien (StatCan) on 2023/09/26 email message: Manner of death order does not reflect the international death certificates and how people read it.   It should be:
0 = Disease
2 = Accident
3 = Intentional self harm
4 = Assault
5 = Legal intervention
6 = War
7 = Could not be determined
8 = Pending investigation
9 = Unknown

Note that Legal intervention should not be coded as an accident, but should have its own code, as in above.

**Comment by cannn** [comment]
Reordering changes is made. In the above request number 1 was skipped but we assume that was a mistake. New order is: 
0: Disease, 1: Accident, 2: Intentional self harm, 3: Assault, 4: Legal intervention, 5: War, 6: Could not be determined, 7: Pending investigation, 9: Unknown
