### ISSUE TITLE
Place of Occurrence value mapping

### ISSUE THREAD

**Issue by samsontu** [ICD-API/electronic-death-certificate-format#2]
As commented by Kathy O'Brien (StatCan) on 2023/09/26 email message: 
School, other institution, public administrative area – have different codes but it should all be one, as it is one term on international medical certificate of cause of death.

**Comment by MihaiHoriaPopescu** [comment]
Reordering changes have been implemented as suggested. The three terms have now merged into one, and the values were updated afterward.
