### ISSUE TITLE
Duration format

### ISSUE THREAD

**Issue by samsontu** [ICD-API/electronic-death-certificate-format#3]
As commented by Kathy O'Brien (StatCan) on 2023/09/26 email message: 
Duration being captured as P2D, for Period 2 days, is challenging to input and challenging for humans to read.  Ultimately, all this is captured for the end user, which is a human.  Is there a reason it is so complicated, why can’t it just be as written.

**Comment by cannn** [comment]
the goal for this format is achieving an unambiguous standard to keep the certificate information. Therefore, using established standards such as ISO 8601 is a good practice as this makes it easier for the software developers to implement the standard when they need to develop software that inputs from this format or outputs to this format.

Human facing tools might (and should) have more flexible human friendly input. We don't expect any form to request the input in this format. In a similar fashion files that are prepared by humans might accept more flexible format than the ISO 8601. We're planning to do this in the excel files that DORIS uses.
